name: apko-minimal-python-scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_REF: ttl.sh/dagger-apko-${{ github.run_id }}:12h

jobs:
  build-apko-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with apko image and publish
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          module: github.com/hampusctl/daggerverse/apko@main
          args: "build --config-file=apko/container.yaml publish --address=${{ env.IMAGE_REF }}"

  scan-apko-image:
    runs-on: ubuntu-latest
    needs: build-apko-image

    steps:
      - name: scan apko image
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          module: github.com/hampusctl/daggerverse/syft@main
          args: "scan --image=${{ env.IMAGE_REF }} export --path=output"

      - name: Add SBOM result to GITHUB_STEP_SUMMARY
        shell: bash
        run: |
          set -euo pipefail
          if test -f "output/report.md"
          then
            cat "output/report.md" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "report.md not found in output/" >> "$GITHUB_STEP_SUMMARY"
            if test -d "output"; then
              ls -la "output" >> "$GITHUB_STEP_SUMMARY"
            fi
            exit 1
          fi

      - name: Upload syft output directory
        uses: actions/upload-artifact@v4
        with:
          name: syft-report
          path: output/
          if-no-files-found: error
          retention-days: 1


      # - name: Scan published image with grype module
      #   uses: dagger/dagger-for-github@v8.2.0
      #   with:
      #     version: "latest"
      #     module: https://github.com/hampusctl/daggerverse.git/grype@main
      #     args: >
      #       scan-image
      #       --image-ref=${{ env.IMAGE_REF }}
      #       export
      #       --path=dist/grype-report.md

      # - name: Upload scan artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dagger-apko-grype-report
      #     path: |
      #       dist/grype-report.md
