name: apko-minimal-python-scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_REF: ttl.sh/dagger-apko-${{ github.run_id }}:12h

jobs:
  build-apko-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with apko image and publish
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          module: github.com/hampusctl/daggerverse/apko@main
          call: |-
            build \
            --config-file=apko/container.yaml \
            publish \
            --address=${{ env.IMAGE_REF }}

  generate-sbom-apko-image:
    runs-on: ubuntu-latest
    needs: build-apko-image

    steps:
      - name: scan apko image
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          module: github.com/hampusctl/daggerverse/syft@main
          call: |-
            scan --image=${{ env.IMAGE_REF }} \
            export \
            --path=syft-output

      - name: Add SBOM result to GITHUB_STEP_SUMMARY
        shell: bash
        run: |
          set -euo pipefail
          if test -f "syft-output/report.md"
          then
            cat "syft-output/report.md" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "report.md not found in syft-output/" >> "$GITHUB_STEP_SUMMARY"
            if test -d "syft-output"; then
              ls -la "syft-output" >> "$GITHUB_STEP_SUMMARY"
            fi
            exit 1
          fi

      - name: Upload syft output directory
        uses: actions/upload-artifact@v4
        with:
          name: syft-report
          path: syft-output/
          if-no-files-found: error
          retention-days: 1

  cve-scan-apko-image:
    runs-on: ubuntu-latest
    needs: generate-sbom-apko-image
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download syft output directory
        uses: actions/download-artifact@v4
        with:
          name: syft-report
          path: syft-output/

      - name: Scan SBOM with grype module
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          module: github.com/hampusctl/daggerverse/grype@main
          call: |-
            scan \
            --sbom=syft-output/sbom.json \
            --config=".grype.yaml" \
            export \
            --path=grype-output

      - name: Add Grype result to GITHUB_STEP_SUMMARY
        shell: bash
        run: |
          set -euo pipefail
          if test -f "grype-output/report.md"
          then
            cat "grype-output/report.md" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "grype report not found in grype-output/" >> "$GITHUB_STEP_SUMMARY"
            if test -d "grype-output"; then
              ls -la "grype-output" >> "$GITHUB_STEP_SUMMARY"
            fi
            exit 1
          fi

      - name: Upload grype output directory
        uses: actions/upload-artifact@v4
        with:
          name: grype-report
          path: grype-output/
          if-no-files-found: error
          retention-days: 1
